import { createHash } from "node:crypto";
import { createSignedWebhookRequest } from "./razorpay.js";
import type {
  CampaignReport,
  PaymentWebhook,
  ScenarioId
} from "./types.js";

export interface RegressionFixture {
  schemaVersion: 1;
  scenario: ScenarioId;
  faultPlan: string[];
  deliveries: Array<{
    eventId: string;
    rawBody: string;
    headers: {
      "x-razorpay-event-id": string;
      "x-razorpay-signature": string;
    };
  }>;
  schedule: Array<{
    offsetMs: number;
    kind: string;
    title: string;
  }>;
  invariant: {
    id: string;
    expression: string;
    expected: string;
    vulnerableObserved: string;
  };
}

export interface RegressionArtifact {
  id: string;
  fileName: string;
  mimeType: "text/typescript";
  scenario: ScenarioId;
  generatedAt: string;
  checksum: string;
  fixture: RegressionFixture;
  source: string;
}

const shared = {
  paymentId: "pay_Q8kwz3nE2s",
  orderId: "order_Q8krp5dH1a",
  amount: 50_000,
  currency: "INR" as const
};

const scenarioEvents: Record<ScenarioId, PaymentWebhook[]> = {
  "duplicate-after-timeout": [
    {
      ...shared,
      eventId: "evt_Q8m4Live",
      event: "payment.captured",
      createdAt: 1_776_926_040
    }
  ],
  "out-of-order-regression": [
    {
      ...shared,
      eventId: "evt_Q8m4Captured",
      event: "payment.captured",
      createdAt: 1_776_925_860
    },
    {
      ...shared,
      eventId: "evt_Q8m4Failed",
      event: "payment.failed",
      createdAt: 1_776_925_800
    }
  ],
  "crash-before-side-effect": [
    {
      ...shared,
      eventId: "evt_Q8m4Crash",
      event: "payment.captured",
      createdAt: 1_776_925_860
    }
  ],
  "concurrent-delivery-race": [
    {
      ...shared,
      eventId: "evt_Q8m4Race",
      event: "payment.captured",
      createdAt: 1_776_925_920
    }
  ],
  "forged-webhook": [
    {
      ...shared,
      eventId: "evt_Q8m4Forged",
      event: "payment.captured",
      createdAt: 1_776_926_520
    }
  ]
};

export function regressionFixtureFromReport(report: CampaignReport): RegressionFixture {
  const invariant = report.invariants[0];
  if (!invariant || report.status !== "failed") {
    throw new Error("A regression artifact requires a proven failed invariant.");
  }

  return {
    schemaVersion: 1,
    scenario: report.scenario,
    faultPlan: [...report.hypothesis.faultPlan],
    deliveries: scenarioEvents[report.scenario].map((webhook) => {
      const signed = createSignedWebhookRequest(webhook);
      return {
        eventId: webhook.eventId,
        rawBody: report.scenario === "forged-webhook"
          ? signed.rawBody.replace('"amount":50000', '"amount":50001')
          : signed.rawBody,
        headers: signed.headers
      };
    }),
    schedule: report.timeline.map(({ offsetMs, kind, title }) => ({
      offsetMs,
      kind,
      title
    })),
    invariant: {
      id: invariant.id,
      expression: invariant.expression,
      expected: invariant.expected,
      vulnerableObserved: invariant.observed
    }
  };
}

function regressionSource(fixture: RegressionFixture): string {
  const serialized = JSON.stringify(fixture, null, 2);
  return `import { describe, expect, it } from "vitest";
import { runCampaign } from "./src/core/campaigns.js";
import { runLiveDuplicateCampaign } from "./src/live/liveCampaign.js";
import type { ProtectionMode } from "./src/core/types.js";

// Generated by PayChaos. Keep this fixture unchanged so the incident remains replayable.
const incident = ${serialized} as const;

async function runAdapter(mode: ProtectionMode) {
  return incident.scenario === "duplicate-after-timeout"
    ? runLiveDuplicateCampaign(mode)
    : runCampaign(incident.scenario, mode);
}

describe(\`PayChaos regression: \${incident.scenario}\`, () => {
  it("reproduces the proven incident against the vulnerable adapter", async () => {
    const report = await runAdapter("vulnerable");

    expect(report.status).toBe("failed");
    expect(report.hypothesis.faultPlan).toEqual(incident.faultPlan);
    expect(report.timeline.map((step) => step.offsetMs)).toEqual(
      incident.schedule.map((step) => step.offsetMs)
    );
    expect(report.invariants).toContainEqual(
      expect.objectContaining({
        id: incident.invariant.id,
        expression: incident.invariant.expression,
        observed: incident.invariant.vulnerableObserved,
        passed: false
      })
    );
  });

  it("verifies the control against the identical incident", async () => {
    const report = await runAdapter("protected");

    expect(report.status).toBe("passed");
    expect(report.hypothesis.faultPlan).toEqual(incident.faultPlan);
    expect(report.timeline.map((step) => step.offsetMs)).toEqual(
      incident.schedule.map((step) => step.offsetMs)
    );
    expect(report.invariants).toContainEqual(
      expect.objectContaining({ id: incident.invariant.id, passed: true })
    );
  });
});
`;
}

export function generateRegressionArtifact(report: CampaignReport): RegressionArtifact {
  const fixture = regressionFixtureFromReport(report);
  const source = regressionSource(fixture);
  const checksum = createHash("sha256").update(source).digest("hex");

  return {
    id: `reg_${checksum.slice(0, 12)}`,
    fileName: `paychaos.${report.scenario}.regression.test.ts`,
    mimeType: "text/typescript",
    scenario: report.scenario,
    generatedAt: new Date().toISOString(),
    checksum,
    fixture,
    source
  };
}
