import { describe, expect, it } from "vitest";
import { runLiveDuplicateCampaign } from "../src/live/liveCampaign.js";

// Generated by PayChaos from a proven live HTTP incident.
const incident = {
  schemaVersion: 1,
  scenario: "duplicate-after-timeout",
  faultPlan: ["Deliver", "Commit", "Timeout response", "Retry same event"],
  delivery: {
    eventId: "evt_Q8m4Live",
    rawBody: "{\"entity\":\"event\",\"account_id\":\"acc_paychaos_demo\",\"event\":\"payment.captured\",\"contains\":[\"payment\"],\"payload\":{\"payment\":{\"entity\":{\"id\":\"pay_Q8kwz3nE2s\",\"entity\":\"payment\",\"amount\":50000,\"currency\":\"INR\",\"status\":\"captured\",\"order_id\":\"order_Q8krp5dH1a\"}}},\"created_at\":1776926040}",
    headers: {
      "x-razorpay-event-id": "evt_Q8m4Live",
      "x-razorpay-signature": "ac29cdacf4b995ce1fd7663d2f167538d27ca655b73527195544d60986e6b8c5"
    }
  },
  scheduleMs: [0, 240, 460, 680, 800, 920, 1_140, 1_300, 1_480],
  invariant: {
    id: "INV-001",
    expression: "fulfilments(payment_id).count <= 1",
    vulnerableObserved: "2"
  }
} as const;

describe(`PayChaos regression: ${incident.scenario}`, () => {
  it("reproduces the incident over live HTTP", async () => {
    const report = await runLiveDuplicateCampaign("vulnerable");

    expect(report.status).toBe("failed");
    expect(report.hypothesis.faultPlan).toEqual(incident.faultPlan);
    expect(report.timeline.map((step) => step.offsetMs)).toEqual(incident.scheduleMs);
    expect(report.invariants).toContainEqual(
      expect.objectContaining({
        id: incident.invariant.id,
        expression: incident.invariant.expression,
        observed: incident.invariant.vulnerableObserved,
        passed: false
      })
    );
  });

  it("verifies the fix against the identical replay", async () => {
    const report = await runLiveDuplicateCampaign("protected");

    expect(report.status).toBe("passed");
    expect(report.hypothesis.faultPlan).toEqual(incident.faultPlan);
    expect(report.timeline.map((step) => step.offsetMs)).toEqual(incident.scheduleMs);
    expect(report.invariants).toContainEqual(
      expect.objectContaining({ id: incident.invariant.id, passed: true })
    );
  });
});
